# Jekyll workshop template
# based on minima theme https://github.com/jekyll/minima

title: go-go gh-pages!
description: > 
  Learn about GitHub pages and Jekyll. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evanwill.github.io/go-go-ghpages" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# figure include: {% include image.html file="cat.jpg" alt="kitten" cap="My cat" width="45%" %}