# Jekyll workshop template
# based on minima theme https://github.com/jekyll/minima

title: Go Go GHpages!
description: > 
  Learn about GitHub pages and Jekyll. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evanwill.github.io/go-go-ghpages" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# note: fig include, {% include image.html file="my-cat.jpg" alt="cat" cap="My cat" width="15%" %}